### ISSUE TITLE
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### ISSUE THREAD

**Issue by Sicky2000** [Derpitron/Discord-OTP-Forcer#69]
### Description

When I run start.bat this error pops up

### Minimal Reproduction

I downloaded the repository and I first manually downloaded the dependencies because I didn't know that setup.bat would've installed them. Then I ran setup.bat and filled out cfg.yml. Then I ran start.bat and this error happens

### Error
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Discord-OTP-Forcer-main\main.py", line 68, in <module>
    userFacing(loadcfg())
  File "C:\Users\user\Desktop\Discord-OTP-Forcer-main\main.py", line 63, in userFacing
    driver = browserBootstrap(cfg)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Discord-OTP-Forcer-main\src\backend.py", line 37, in browserBootstrap
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 40, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\driver.py", line 51, in get_driver_version_to_download
    self._driver_to_download_version = self._version if self._version not in (None, "latest") else self.get_latest_release_version()
                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 62, in get_latest_release_version
    resp = self._http_client.get(url=latest_release_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\http.py", line 37, in get
    self.validate_response(resp)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
```
### Operating System Version

Windows 11

### Python Version

3.11.4

### Program Version 

0ac1483

**Comment by Derpitron** [comment]
I am looking into this issue.

**Comment by Derpitron** [comment]
This seems to be an issue with `webdriver_manager` Python package.

https://github.com/SergeyPirogov/webdriver_manager/issues/536 Follow the main issue here:

**Comment by Sicky2000** [comment]
Thanks so much. It worked fine. I hope they will merge the pull request soon. I'll close the issue now
