### ISSUE TITLE
[Bug]: keyerror: TOTP

### ISSUE THREAD

**Issue by SMG54321** [Derpitron/Discord-OTP-Forcer#91]
### Description

every time i try to run the program i gotten some sort of key error relating to something known as TOTP. I have filled everything to the best of my abilities (thief changed the password). i am not code savy, please tell me what this means!

### Minimal Reproduction

heppens every time i try to run the program (i censored my name in the error log)

### Error

Traceback (most recent call last):
  File "C:\Users\[IRL name]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\main.py", line 68, in <module>
    userFacing(load_configuration())
  File "C:\Users\[IRL name]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\main.py", line 64, in userFacing
    bootstrap_login_page(driver, configuration)
  File "C:\Users\[IRL name]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\src\backend.py", line 117, in bootstrap_login_page
    code_entry(driver, login_fields, configuration)
  File "C:\Users\[IRL name]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\src\backend.py", line 178, in code_entry
    login_fields['TOTP'].send_keys(totp_code)

### Operating System Version

dunno

### Python Version

3.12

### Program Version 

latest

**Comment by Derpitron** [comment]
The error you sent isn't visible. Re run the program and send a screenshot of the terminal output.

**Comment by Derpitron** [comment]
@SMG54321 please try to repeat this error and let us know if you face any problems.

**Comment by Derpitron** [comment]
Reopening as this issue has been observed before.

**Comment by Derpitron** [comment]
Believe it or not this issue may actually be related to another one of #95 's various glitches. I'll mark this as duplicate for now.
